# Generated by Django 2.1.7 on 2020-09-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20190611_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
